### PR TITLE
Travis testing with Seneca 3 and added contributors

### PR DESCRIPTION
**Pull request by shanel262**

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@shanel262 Please increase -t to 70 👍

**Comment by shanel262** [comment]
@mcdonnelldean Done 👍

**Comment by mihaidma** [comment]
restarted one of the tests. As long as tests fail this can't be merged. It was previously working, also it is seneca 3 comptible.

**Comment by shanel262** [comment]
@mihaidma Should already be passing, the reason it failed was due to me changing the coverage to 70 instead of 50.

**Comment by mihaidma** [comment]
:+1:

**Pull request merged**
